[tool.poetry]
name = "mdcor"
version = "0.1.0"
description = ""
authors = ["infocornouaille <90894019+infocornouaille@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
